# Site settings
title: "Fatih Akturk"
email: f.akturk@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: "fakturk.ml"
url: "fakturk.ml"
title_description: "Machine Learning Researcher <a href=\" https://squarefalcon.com">@SquareFalcon</a> "
title_image: "https://www.gravatar.com/avatar/f0ed8a368e164c2a86487c137fd9995e?s=500&d=mm"
google_analytics: "UA-138588166-1"
disqus_account: cartenoire
github_repository: https://github.com/fakturk/fakturk.ml
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: fakturk
github_username:  fakturk
instagram_username: 
reddit_username: 
linkedin_link: http://linkedin.com/in/fatihakturk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
